Resources:
  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGatewayRestApi # serverless default Rest API logical ID
          - RootResourceId
      PathPart: TO_BE_REPLACED # the endpoint in your API that is set as proxy
      RestApiId:
        Ref: ApiGatewayRestApi
  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      ResourceId:
        Ref: TO_BE_REPLACED
      RestApiId:
        Ref: ApiGatewayRestApi
      HttpMethod: GET
      MethodResponses:
        - StatusCode: 200
      Integration:
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: TO_BE_REPLACED
        IntegrationResponses:
          - StatusCode: 200
